name: website

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - name: Install dependencies
        run: |
          uv venv -p 3.13
          . .venv/bin/activate
          uv pip install -r requirements.txt
      - name: Generate Everything
        run: |
          cd portfolio
          cargo run
          cd ..
      - uses: jmservera/libreoffice-action@v0.2
        name: Install Carlito font and LibreOffice CLI to convert resume to PDF
        with:
          command: |
            mkdir -p ~/.fonts
            wget -qO- https://github.com/google/fonts/raw/main/ofl/carlito/Carlito-Regular.ttf -O ~/.fonts/Carlito-Regular.ttf
            wget -qO- https://github.com/google/fonts/raw/main/ofl/carlito/Carlito-Bold.ttf -O ~/.fonts/Carlito-Bold.ttf
            wget -qO- https://github.com/google/fonts/raw/main/ofl/carlito/Carlito-Italic.ttf -O ~/.fonts/Carlito-Italic.ttf
            wget -qO- https://github.com/google/fonts/raw/main/ofl/carlito/Carlito-BoldItalic.ttf -O ~/.fonts/Carlito-BoldItalic.ttf
            fc-cache -f
            libreoffice --headless --convert-to pdf:writer_pdf_Export docs/source/_static/resume.docx --outdir docs/source/_static
      - name: Build site
        run: |
          . .venv/bin/activate
          make -C docs html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
